seeder:
  file: seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/listings.rb
    page_type: listings
    disabled: false
  - file: ./parsers/details.rb
    page_type: details
    disabled: false

exporters:
  - file: ./exporters/produtcs_last10_json.yaml
    disable: false